In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [8]:
df = pd.read_csv(r"C:\Users\dell\Documents\ML\student_data1.csv")
print(df.head())

   Study_Hours  Attendance  Pass
0            1          45     0
1            2          55     0
2            3          60     0
3            4          65     0
4            5          75     1


In [9]:
x = df[['Study_Hours','Attendance']]
y = df[['Pass']]

In [21]:
x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,random_state=42
)


In [22]:
x


,Study_Hours,Attendance
0,1,45
1,2,55
2,3,60
3,4,65
4,5,75
5,6,80
6,7,85
7,8,90
8,9,95
9,10,98


In [23]:
y

,Pass
0,0
1,0
2,0
3,0
4,1
5,1
6,1
7,1
8,1
9,1


In [29]:
model =  LogisticRegression()

In [30]:
model.fit(x_train,y_train.values.ravel())

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [31]:
y_pred = model.predict(x_test)
print(y_pred)

[0 0 1 0 1 1 1 1 0 0 1]


In [18]:
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 1.0


In [32]:
Study_Hours = float(input("Enter Study Hours:"))
attendance = float(input("Enter Attendance Percentage:"))

Enter Study Hours: 10
Enter Attendance Percentage: 89


In [35]:
new_student = [[Study_Hours,attendance]]
prediction = model.predict(new_student)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [34]:
if prediction[0] == 1:
    print("Result: Pass")
else:
    print("Result: Fail")

Result: Pass


In [36]:
# Assignment 2: Loan Approval Prediction

In [37]:
import pandas as pd

In [38]:
import numpy as np

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
from sklearn.linear_model import LogisticRegression

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [45]:
df = pd.read_csv(r"C:\Users\dell\Documents\ML\student_data2.csv")
print(df.head())

   Income  Credit_Score  Approved
0   25000           600       0.0
1   70000           780       1.0
2   35000           620       0.0
3   55000           710       1.0
4   48000           690       0.0


In [4]:
import numpy as np
np.random.seed(42)
income = np.random.randint(20000,100001,100)
credit_score = np.random.randint(550,851,100)
approved = []

for i in range(100):
    if income[i] >= 50000 and credit_score[i] >= 700:
        approved.append(1)
    else:
        approved.append(0)

In [9]:
import pandas as pd
df = pd.DataFrame({
    'Income':income,
    'Credit_score':credit_score,
    'Loan_Approved':approved
})

In [10]:
print("First 5 Records:")
print(df.head())

First 5 Records:
   Income  Credit_score  Loan_Approved
0   35795           611              0
1   20860           765              0
2   96820           842              1
3   74886           648              0
4   26265           721              0


In [12]:
X = df[['Income', 'Credit_score']]
y = df['Loan_Approved']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, random_state=42
)


In [17]:
X

,Income,Credit_score
0,35795,611
1,20860,765
2,96820,842
3,74886,648
4,26265,721
...,...,...
95,28392,843
96,50535,829
97,98603,647
98,72256,747


In [18]:
y

0     0
1     0
2     1
3     0
4     0
     ..
95    0
96    1
97    0
98    1
99    1
Name: Loan_Approved, Length: 100, dtype: int64

In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [23]:
y_pred = model.predict(X_test)
print("Predicted Values:")
print(y_pred)

Predicted Values:
[0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]


In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[17  0]
 [ 0  3]]


In [27]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy * 100, "%")

Accuracy: 100.0 %


In [28]:
#Assignment 3: Customer Purchase Prediction

In [29]:
import pandas as pd

In [30]:
import numpy as np

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [32]:
np.random.seed(42)

age = np.random.randint(18, 60, 100)
income = np.random.randint(10000, 100000, 100)

purchased = []

for a, i in zip(age, income):
    if a > 30 and i > 40000:
        purchased.append(1)
    else:
        purchased.append(0)

data = pd.DataFrame({
    "Age": age,
    "Monthly_Income": income,
    "Purchased": purchased
})

In [33]:
print("First 10 Records:")
print(data.head(10))

First 10 Records:
   Age  Monthly_Income  Purchased
0   56           18392          0
1   46           40535          1
2   32           88603          1
3   25           62256          0
4   38           99135          1
5   56           45222          1
6   36           87373          1
7   40           89575          1
8   28           94651          0
9   28           73335          0


In [38]:
X = data[["Age", "Monthly_Income"]]
y = data["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size=0.2, random_state=42
)


In [39]:
X

,Age,Monthly_Income
0,22,15000
1,35,50000
2,28,22000
3,40,65000
4,30,35000
...,...,...
96,28,27000
97,45,76000
98,22,16000
99,41,62000


In [40]:
y

0      0
1      1
2      0
3      1
4      0
      ..
96     0
97     1
98     0
99     1
100    1
Name: Purchased, Length: 101, dtype: int64

In [41]:
model = LogisticRegression()
model.fit(X_train, y_train)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [42]:
y_pred = model.predict(X_test)
print("Predicted Values:")
print(y_pred)


Predicted Values:
[1 0 0 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1]


In [43]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 1.0
Confusion Matrix:
[[10  0]
 [ 0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        11

    accuracy                           1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21



In [45]:
import pandas as pd
new_customer = [[35, 50000]]
prediction = model.predict(new_customer)
if prediction[0] == 1:
    print("Prediction: Customer Will Purchase")
else:
    print("Prediction: Customer Will Not Purchase")

Prediction: Customer Will Purchase


C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [46]:
#Assignment 4: Employee Attrition Prediction

In [47]:
import pandas as pd

In [48]:
import numpy as np

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [57]:
daa = pd.read_csv(r"C:\Users\dell\Documents\ML\Experience_year.csv")
print(data)

    Experience_Years  Overtime_Hours  Salary  Left_Company
0                  1              30   25000             1
1                  5               5   60000             0
2                  2              25   30000             1
3                  8              10   75000             0
4                  3              28   35000             1
..               ...             ...     ...           ...
95                 4              21   43000             1
96                 8              10   81000             0
97                 2              34   30000             1
98                 7              13   74000             0
99                 3              27   35000             1

[100 rows x 4 columns]


In [58]:
np.random.seed(42)
experience = np.random.randint(1, 11, 100)
overtime = np.random.randint(0, 41, 100)
salary = np.random.randint(20000, 100001, 100)
left = []
for i in range(100):
    if overtime[i] > 20 and salary[i] < 50000:
        left.append(1)
    else:
        left.append(0)


In [59]:
data = pd.DataFrame({
    "Experience_Years": experience,
    "Overtime_Hours": overtime,
    "Salary": salary,
    "Left_Company": left
})

In [60]:
data.to_csv("employee_attrition.csv", index=False)
print("Data saved successfully!")


Data saved successfully!


In [61]:
data = pd.read_csv("employee_attrition.csv")

In [62]:
X = data[["Experience_Years", "Overtime_Hours", "Salary"]]
y = data["Left_Company"]

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size=0.2, random_state=42
)



In [65]:
X

,Experience_Years,Overtime_Hours,Salary
0,7,11,54698
1,4,33,42671
2,8,32,45184
3,5,22,62107
4,7,23,71663
...,...,...,...
95,10,37,76491
96,9,23,38589
97,7,4,63484
98,9,33,56212


In [66]:
y

0     0
1     1
2     1
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    0
Name: Left_Company, Length: 100, dtype: int64

In [67]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [68]:
y_pred = model.predict(X_test)

In [69]:
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.9


In [70]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.92      0.92      0.92        12
           1       0.88      0.88      0.88         8

    accuracy                           0.90        20
   macro avg       0.90      0.90      0.90        20
weighted avg       0.90      0.90      0.90        20



In [78]:
new_employee = [[3, 28, 35000]]
prediction = model.predict(new_employee)
if prediction[0] == 1:
    print("Employee is likely to Leave the Company")
else:
    print("Employee is likely to Stay in the Company")

Employee is likely to Leave the Company


C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [79]:
#Assignment 5: Diabetes Risk Prediction

In [80]:
import pandas as pd

In [81]:
import numpy as np

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [83]:
data = pd.read_csv(r"C:\Users\dell\Documents\ML\Blood_Sugar.csv")
print(data)

    Age  BMI  Blood_Sugar  Diabetes
0    25   22           90         0
1    30   24           95         0
2    28   23           88         0
3    35   26          110         0
4    40   27          120         0
..  ...  ...          ...       ...
93   51   34          193         1
94   53   35          203         1
95   55   36          213         1
96   57   37          223         1
97   60   38          235         1

[98 rows x 4 columns]


In [84]:
X = data[["Age", "BMI", "Blood_Sugar"]]
y = data["Diabetes"]

In [85]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size=0.2, random_state=42
)


In [86]:
X

,Age,BMI,Blood_Sugar
0,25,22,90
1,30,24,95
2,28,23,88
3,35,26,110
4,40,27,120
...,...,...,...
93,51,34,193
94,53,35,203
95,55,36,213
96,57,37,223


In [87]:
y

0     0
1     0
2     0
3     0
4     0
     ..
93    1
94    1
95    1
96    1
97    1
Name: Diabetes, Length: 98, dtype: int64

In [88]:
model = LogisticRegression()
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [89]:
y_pred = model.predict(X_test)

In [90]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
Confusion Matrix:
[[11  0]
 [ 0  9]]
