In [3]:
import numpy as np
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]
])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
# 1.Extract the first row. 
arr[0]

array([1, 2, 3, 4, 5])

In [6]:
#2.	Extract the last row
arr[-1]

array([26, 27, 28, 29, 30])

In [7]:
#3.	Extract the third column
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [8]:
#4.	Extract the first three rows. 
arr[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
#5.	Extract the last three rows
arr[-3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
#6.Extract the first two columns
arr[:, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [11]:
#7.	Extract the last two columns
arr[:, -2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [12]:
#8.	Extract the subarray containing rows 1 to 3 and columns 2 to 4. 
arr[1:4, 2:5]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [13]:
#9.	Extract all rows from index 2 onward. 
arr[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
#10.Extract all columns from index 3 onward. 
arr[:, 3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [15]:
#11.Extract every second row. 
arr[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [16]:
#12.Extract every second column
arr[:, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25],
       [26, 28, 30]])

In [17]:
#13.Extract the bottom-right 3×2 block. 
arr[-3:, -2:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [18]:
#14.Extract the top-left 4×3 block. 
arr[:4, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [19]:
#15.Reverse the order of rows
arr[::-1]

array([[26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [20]:
#16.Reverse the order of columns
arr[:, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21],
       [30, 29, 28, 27, 26]])

In [21]:
#17.Reverse both rows and columns. 
arr[::-1, ::-1]

array([[30, 29, 28, 27, 26],
       [25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [22]:
#18.Extract the middle 2×3 block
arr[1:3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [23]:
#19.Extract the first and last rows only. 
arr[[0, -1]]

array([[ 1,  2,  3,  4,  5],
       [26, 27, 28, 29, 30]])

In [24]:
#20.Extract the first and last columns only. 
arr[:, [0, -1]]

array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25],
       [26, 30]])

In [25]:
#21.Extract all odd-indexed rows
arr[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [26]:
#22.Extract all even-indexed columns
arr[:, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25],
       [26, 28, 30]])

In [27]:
#23.Extract the element at row index 4 and column index 2. 
arr[4, 2]

np.int64(23)

In [28]:
#24.Extract the entire row containing the value 18. 
arr[3]

array([16, 17, 18, 19, 20])

In [29]:
#25.Extract the entire column containing the value 14. 
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

In [30]:
#26.Extract the four corner elements. 
arr[[0, 0, -1, -1], [0, -1, 0, -1]]

array([ 1,  5, 26, 30])

In [31]:
#27.Extract the central column only. 
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [32]:
#28.Extract rows 1 to 4 and every second column. 
arr[1:5, ::2]

array([[ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [33]:
#29.Extract every row but only columns with indices 1, 2, and 3. 
arr[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [34]:
#30.Extract a 2×2 block from the center of the array.
arr[1:3, 1:3]

array([[ 7,  8],
       [12, 13]])